version: smartide/v0.2
orchestrator:
  type: allinone
  version: 3
workspace:
  dev-container:
    service-name: ruoyi-cloud-dev
    ports: # 申明端口
      tools-webide-vscode: 6800
      tools-ssh: 6822
      tools-phpmyadmin: 8090
      tools-nacos: 8848
      apps-ruoyi-ui: 8000
      apps-ruoyi-admin: 8080
    
    ide-type: vscode
    volumes: 
      git-config: true
      ssh-key: true
    command:
      - cd /home/project
      - echo "------1.执行maven打包--------"
      - mvn package
      - echo "------2.安装Java插件扩展包--------"
      - code --install-extension vscjava.vscode-java-pack
      - echo "------3.修改hosts文件配置--------"
      - sudo chmod o+w /etc/hosts && echo "127.0.0.1 ruoyi-nacos" >> /etc/hosts && echo "127.0.0.1 ruoyi-gateway" >> /etc/hosts && sudo chmod o-w /etc/hosts
      - echo "------4.前端构建--------"
      - cd ruoyi-ui && npm config set registry https://registry.npmmirror.com && npm install
      - echo "------5.应用依赖第三方组件启动（Docker方式）--------"
      - cd ../.ide/ && chmod 777 -R mysql && chmod 777 -R nacos && docker compose -f docker-compose-debug.yml up -d
      - echo "------6.安装Docker管理工具扩展包--------"
      - code --install-extension ms-azuretools.vscode-docker

  kube-deploy-files: "ruoyi-k8s-deployment-vmlc.yaml" 
  docker-compose-file: "ruoyi-docker-compose-vmlc.yaml"