version: smartide/v0.2
orchestrator:
  type: k8s
  version: 3
workspace:
  dev-container:
    service-name: ruoyi-cloud-dev
    
    ports: # 申明端口
      tools-webide-idea: 6800
      tools-ssh: 6822
      tools-phpmyadmin: 8090
      tools-nacos: 8848
      tools-sonar: 9000
      apps-ruoyi-ui: 8000
      apps-ruoyi-admin: 8080
    
    ide-type: vscode
    volumes: 
      git-config: true
      ssh-key: true
    command:
      - mvn package

  kube-deploy-files: "ruoyi-k8s-deployment.yaml"