version: smartide/v0.2
orchestrator:
  type: k8s
  version: 3
workspace:
  dev-container:
    service-name: ruoyi-cloud-dev
    webide-port: 6800
    
    ports: # 申明端口
      tools-webide-vscode: 6800
      tools-ssh: 6822
      apps-application: 8080
    
    ide-type: vscode
    volumes: 
      git-config: true
      ssh-key: true
    command:
      - mvn package

  kube-deploy-files: "ruoyi-k8s-vmlc-pod.yaml"