version: smartide/v0.1
orchestrator:
  type: docker-compose
  version: 3
workspace:
  dev-container:
    service-name: ruoyi-dev
    ports:
      tools-webide-idea: 6800
      tools-ssh: 6822
      apps-application: 8080
    ide-type: vscode
    volumes:
      git-config: true
      ssh-key: true

  kube-deploy-files: "*-deployment.yaml"
