version: smartide/v0.2
orchestrator:
  type: k8s
  version: 3
workspace:
  dev-container:
    service-name: ruoyi-dev
    
    ports: # 申明端口
      tools-webide-jb: 6800
      tools-ssh: 6822
      apps-ruoyi-ui: 8000
      apps-ruoyi-admin: 8080
    
    ide-type: jb-projector
    volumes: 
      git-config: true
      ssh-key: true
    command:
      - mvn package

  kube-deploy-files: "ruoyi-k8s-muticontainer-deployment.yaml"