version : '3.8'
services:
  ruoyi-mysql:
    image: registry.cn-hangzhou.aliyuncs.com/smartide/mysql:8.0.21
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --init-file=/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: mysql --user=root --password=password -e 'SHOW DATABASES LIKE "ry-config";'
      interval: 3s
      timeout: 1s
      retries: 16
    restart: always
    expose:
      - 3306
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - './mysql/local:/docker-entrypoint-initdb.d'

  ruoyi-nacos:
    container_name: ruoyi-nacos
    image: registry.cn-hangzhou.aliyuncs.com/boathouse/nacos-server:v2.0.4
    restart: always
    build:
      context: './nacos'
    environment:
      MODE: standalone
    volumes:
      - './nacos/conf/application.properties:/home/nacos/conf/application.properties'
    expose:
      - 8848
      - 9848
      - 9849
    ports:
      - 8848:8848
      - 9848:9848
      - 9849:9849
    healthcheck:
      test: curl -f http://localhost:8848/nacos/index.html || kill 1
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 30s
    depends_on:
      ruoyi-mysql:
        condition: service_healthy

  ruoyi-phpmyadmin:
    image: registry.cn-hangzhou.aliyuncs.com/boathouse/phpmyadmin:5.0.4-apache
    restart: always
    expose:
      - 8090
    ports:
      - 8090:80
    environment:
      PMA_ARBITRARY: "1"

  ruoyi-redis:
    image: registry.cn-hangzhou.aliyuncs.com/smartide/redis:6.0.6
    restart: always
    expose:
      - 6379
    ports:
      - "6379:6379"