---

apiVersion: v1
kind: Pod
metadata:
  name: ruoyi-cloud-dev-pod
  annotations:
    io.kubernetes.cri-o.userns-mode: "auto:size=65536"
spec:
  selector:
    matchLabels:
      ruoyi-cloud.service: ruoyi-cloud
  runtimeClassName: sysbox-runc
  containers:
  - name: ruoyi-cloud-dev-container
    image: registry.cn-hangzhou.aliyuncs.com/smartide/smartide-java-v2-vscode-vmlc
    command: ["/sbin/init"]
  restartPolicy: Never

---

apiVersion: v1
kind: Service
metadata:
  name: ruoyi-cloud-dev
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
    - name: "6800"
      port: 6800
      targetPort: 3000
    - name: "6822"
      port: 6822
      targetPort: 22
  selector:
    ruoyi-cloud.service: ruoyi-cloud
status:
  loadBalancer: {}

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ruoyi-cloud-network
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              ruoyi-cloud/smartide-network: "true"
  podSelector:
    matchLabels:
      ruoyi-cloud/smartide-network: "true"