apiVersion: v1
kind: Service
metadata:
  name: ruoyi-auth
spec:
  ports:
    - name: "9200"
      port: 9200
      targetPort: 9200
  selector:
    app: ruoyi-auth
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ruoyi-auth
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: ruoyi-auth
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ruoyi-auth
    spec:
      containers:
      - name: ruoyi-auth
        image: registry.cn-hangzhou.aliyuncs.com/boathouse/ruoyi-auth:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 9200