apiVersion: v1
kind: Service
metadata:
  name: ruoyi-nacos
spec:
  ports:
    - name: "8848"
      port: 8848
      targetPort: 8848
    - name: "9848"
      port: 9848
      targetPort: 9848
    - name: "9849"
      port: 9849
      targetPort: 9849
  selector:
    app: ruoyi-nacos
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ruoyi-nacos
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: ruoyi-nacos
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ruoyi-nacos
    spec:
      containers:
      - name: ruoyi-nacos
        image: registry.cn-hangzhou.aliyuncs.com/boathouse/ruoyi-nacos:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /nacos/index.html
            port: 8848
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        env:
          - name: MODE
            value: "standalone"
        ports:
          - containerPort: 8848
          - containerPort: 9848
          - containerPort: 9849