apiVersion: v1
kind: Service
metadata:
  name: ruoyi-gateway
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    app: ruoyi-gateway
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ruoyi-gateway
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: ruoyi-gateway
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ruoyi-gateway
    spec:
      containers:
      - name: ruoyi-gateway
        image: registry.cn-hangzhou.aliyuncs.com/boathouse/ruoyi-gateway:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080