apiVersion: v1
kind: Service
metadata:
  name: ruoyi-redis
spec:
  ports:
    - port: 6379
  selector:
    app: ruoyi-redis
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ruoyi-redis
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: ruoyi-redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ruoyi-redis
    spec:
      containers:
      - name: ruoyi-redis
        image: registry.cn-hangzhou.aliyuncs.com/boathouse/ruoyi-redis:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 6379
        args:
          - "/home/ruoyi/redis/redis.conf"