apiVersion: v1
kind: Service
metadata:
  name: ruoyi-nginx
spec:
  type: NodePort
  ports:
    - name: "8000"
      port: 8000
      targetPort: 80
      nodePort: 30068
  selector:
    app: ruoyi-nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ruoyi-nginx
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: ruoyi-nginx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ruoyi-nginx
    spec:
      containers:
      - name: ruoyi-nginx
        image: registry.cn-hangzhou.aliyuncs.com/boathouse/ruoyi-nginx:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 80